### ISSUE TITLE
Error on /updateTags

### ISSUE THREAD

**Issue by Wyrrrd** [mruac/hydrus-remote-tagging#4]
I am not too good at reading flask, but [this](https://hydrusnetwork.github.io/hydrus/developer_api.html#tags) seems to indicate something is broken because the API tag format changed recently.

<details><summary>Error message</summary>

```
"POST /updateTags HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/src/app/server.py", line 177, in updateTags
    file_tags = session['metadata']['service_keys_to_statuses_to_tags'][tag_repo_key]
KeyError: 'service_keys_to_statuses_to_tags'
```
</details>

**Comment by mruac** [comment]
Correct, I do apologise I don't update my hydrus client as frequently, but it looks like I'll need to include the new `tags` object in the code. I'll look into this sometime this week.

**Comment by Wyrrrd** [comment]
Sorry if this sounded demanding, I just meant to inform. Take your time :)

**Comment by mruac** [comment]
No, all good - turns out I hadn't coded the if condition to check the api version before deciding which object to set `file_tags` to. Just had to move it around a bit.
Seems dev finally depreciated the old tag object in hydrus client v514.
